### ISSUE TITLE
Does not pass view-convention tests.

### ISSUE THREAD

**Issue by latentflip** [AmpersandJS/ampersand-input-view#26]
If setValue is called before the view is rendered (as it is in ampersandjs/ampersand-view-conventions) this line explodes: https://github.com/AmpersandJS/ampersand-input-view/blob/master/ampersand-input-view.js#L128

**Comment by cdaringe** [comment]
Cross-referencing https://github.com/AmpersandJS/ampersand-form-view/issues/28

**Comment by cdaringe** [comment]
Closing with #59
