### ISSUE TITLE
Render should return `this`?

### ISSUE THREAD

**Issue by mmacaula** [AmpersandJS/ampersand-input-view#35]
It's not an [official view convention](http://ampersandjs.com/learn/view-conventions) but I was wondering if the render method should follow `ampersand-view` and return `this` after it's done rendering.  Seems confusing to not do so.  I'd be happy to submit a PR with tests if you agree

**Comment by lukekarrys** [comment]
@mmacaula Good catch! I would agree that all render methods should `return this`.

**Comment by lukekarrys** [comment]
Closed by #36.
