### ISSUE TITLE
Returns an empty string for empty input of type number causing casting errors

### ISSUE THREAD

**Issue by pgilad** [AmpersandJS/ampersand-input-view#39]
when trying to cast back values the model will not be able to cast empty string `''` to `number` and thus throw a casting error

**Comment by kamilogorek** [comment]
@pgilad could you please provide a test case?

**Comment by wraithgar** [comment]
When this goes out I think it should fix this: https://github.com/AmpersandJS/ampersand-input-view/pull/51

**Comment by wraithgar** [comment]
@pgilad can you test v4.0.1 and see if it works for you now

**Comment by pgilad** [comment]
Yeah I'll give it a go soon, thx!

**Comment by pgilad** [comment]
Fixed as far as I'm concerned. Thanks!

**Comment by pbastia** [comment]
Hi, this bugfix now raises a question for me: how do you make a difference between an empty field and a field containing the number '0'? Given that an empty string will default to 0 when the input view calls the `clean` method?

Thanks,

Pierre

**Comment by kamilogorek** [comment]
Hey @pbastia, an empty string will be used in that case and default is indeed an empty string, not 0.

```js
initialize: function (spec) {
    var value = !spec.value && spec.value !== 0 ? '' : spec.value;
}

(...)

clean: function (val) {
    return (this.type === 'number') ? Number(val) : val.trim();
}
```
