### ISSUE TITLE
Tests run multiple times on input change

### ISSUE THREAD

**Issue by malbonesi** [AmpersandJS/ampersand-input-view#56]
When validating an input field, the tests run multiple times per input change. `runTests()` is called 3 times per input change while that input is invalid, and then 7 times once a valid value starts (I'm just checking length).

This gist just logs a console message as a simple test: http://requirebin.com/?gist=a728e6caf6f7a0eff022, but if you start typing you'll see the tests run multiple times.

Removing `cache: false` on the `valid` derived property stops this from happening.

I feel like it should be the case where validation only happens one once per input change, but maybe there is something else requiring cache to be false.

**Comment by gonsfx** [comment]
The `cache` property for the `valid` derived was set to `false` in 0bd5bd1

**Comment by wraithgar** [comment]
I agree that eventually valid's cache setting should be configurable. However changing that only fixes a symptom, not a problem.  It really shouldn't be evaluating the tests that many times on input changes, regardless.  Will have to come up w/ a fix for this that is a little more optimized.
