### ISSUE TITLE
Mark as invalid with message from server?

### ISSUE THREAD

**Issue by gonsfx** [AmpersandJS/ampersand-input-view#60]
Is there an easy way to mark an `ampersand-input-view` as invalid with a serverside error message?

e.g. i have an registration-view with email and password fields and get serverside validation information for one or both.

**Comment by wraithgar** [comment]
I wrote an async form validation example gist awhile back, it may be what you're looking for:

https://gist.github.com/wraithgar/7fc72e5fb72502c99dcf

You would of course want to do an ajax call in lieu of the setTImeout call but hopefully this gets you started at least.
